name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn package -Dmaven.test.skip=true
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: /home/runner/work/fawry-jpa-practice/fawry-jpa-practice/target/spring-data-jpa-practice-0.0.1-SNAPSHOT.jar
